### ISSUE TITLE
Add To-Do CLI Application that written in C++

### ISSUE THREAD

**Issue by Kei-K23** [codecrafters-io/build-your-own-x#1133]
### Main programming language
`C++`

### Tutorial title
To-Do CLI Application in C++

### Tutorial URL
https://github.com/Kei-K23/todo-cli

### Category
* [ ] 3D Renderer
* [ ] Augmented Reality
* [ ] BitTorrent Client
* [ ] Blockchain / Cryptocurrency
* [ ] Bot
* [x] Command-Line Tool
* [ ] Database
* [ ] Docker
* [ ] Emulator / Virtual Machine
* [ ] Front-end Framework / Library
* [ ] Game
* [ ] Git
* [ ] Network Stack
* [ ] Neural Network
* [ ] Operating System
* [ ] Physics Engine
* [ ] Programming Language
* [ ] Regex Engine
* [ ] Search Engine
* [ ] Shell
* [ ] Template Engine
* [ ] Visual Recognition System
* [ ] Voxel Engine
* [ ] Web Search Engine
* [ ] Web Server
* [ ] Uncategorized

**Comment by FabriLluvia** [comment]
https://github.com/codecrafters-io/build-your-own-x/pull/1270
